# Generated by Django 5.2 on 2025-05-07 21:26

import services.modelServices.generate_id
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='analisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analisis', models.TextField(max_length=450000)),
            ],
        ),
        migrations.CreateModel(
            name='dream',
            fields=[
                ('id', models.CharField(default=services.modelServices.generate_id.generate_id, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='emotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=80)),
                ('description', models.TextField(max_length=900)),
                ('time', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='psychologistExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(max_length=500)),
            ],
        ),
    ]
