# Generated by Django 5.2 on 2025-05-07 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dreams', '0001_initial'),
        ('psychologists', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analisis',
            name='psychologist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychologists.psychologist'),
        ),
        migrations.AddField(
            model_name='dream',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analisis',
            name='dream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreams.dream'),
        ),
        migrations.AddField(
            model_name='dream',
            name='emotions',
            field=models.ManyToManyField(to='dreams.emotions'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='psychologistexercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreams.exercise'),
        ),
        migrations.AddField(
            model_name='psychologistexercise',
            name='psychologist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychologists.psychologist'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='psychologist',
            field=models.ManyToManyField(blank=True, through='dreams.psychologistExercise', to='psychologists.psychologist'),
        ),
    ]
