# Generated by Django 5.2.7 on 2025-10-26 00:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisis',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dream',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
