# Generated by Django 5.2.7 on 2025-11-12 14:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionalCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#9675bc', max_length=7)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Categoría Emocional',
                'verbose_name_plural': 'Categorías Emocionales',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmotionalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(max_length=5000)),
                ('entry_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mood', models.CharField(choices=[('very_bad', 'Muy Mal'), ('bad', 'Mal'), ('neutral', 'Neutral'), ('good', 'Bien'), ('very_good', 'Muy Bien')], max_length=20)),
                ('intensity', models.IntegerField(default=5)),
                ('tags', models.CharField(blank=True, max_length=500, null=True)),
                ('ai_analysis', models.TextField(blank=True, max_length=10000, null=True)),
                ('ai_analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('is_private', models.BooleanField(default=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(blank=True, related_name='entries', to='dreams.emotionalcategory')),
                ('emotions', models.ManyToManyField(blank=True, related_name='emotional_entries', to='dreams.emotions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotional_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrada Emocional',
                'verbose_name_plural': 'Entradas Emocionales',
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmotionalMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('milestone_date', models.DateField()),
                ('icon', models.CharField(default='star', max_length=50)),
                ('color', models.CharField(default='#f1b3be', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='milestone', to='dreams.emotionalentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotional_milestones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hito Emocional',
                'verbose_name_plural': 'Hitos Emocionales',
                'ordering': ['-milestone_date'],
            },
        ),
        migrations.AddIndex(
            model_name='emotionalentry',
            index=models.Index(fields=['user', '-entry_date'], name='dreams_emot_user_id_f21e29_idx'),
        ),
        migrations.AddIndex(
            model_name='emotionalentry',
            index=models.Index(fields=['user', 'mood'], name='dreams_emot_user_id_42979c_idx'),
        ),
    ]
