# Generated by Django 5.2 on 2025-05-14 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psychologists', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='psychologist',
            old_name='starDate',
            new_name='startDate',
        ),
    ]
