# Generated by Django 5.2.7 on 2025-10-26 00:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologists', '0003_rename_stardate_psychologist_startdate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='forms',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='emotion',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='university',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='form_response',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_score', models.IntegerField(blank=True, help_text='Suma de los valores de las answers', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_responses', to=settings.AUTH_USER_MODEL)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='psychologists.forms')),
            ],
        ),
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField(max_length=1000)),
                ('min_value', models.IntegerField(default=0)),
                ('max_value', models.IntegerField(default=10)),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychologists.psychologist')),
            ],
        ),
        migrations.AddField(
            model_name='forms',
            name='questions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='forms', to='psychologists.questions'),
        ),
        migrations.CreateModel(
            name='answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='psychologists.form_response')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychologists.questions')),
            ],
            options={
                'unique_together': {('response', 'question')},
            },
        ),
    ]
