# Generated by Django 5.2 on 2025-05-15 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologists', '0004_psychologist_id_alter_psychologist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
