# Generated by Django 5.2.7 on 2025-11-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologists', '0004_forms_psychologist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forms',
            name='questions',
        ),
        migrations.AddField(
            model_name='forms',
            name='questions',
            field=models.ManyToManyField(related_name='forms', to='psychologists.questions'),
        ),
    ]
