# Generated by Django 5.2.7 on 2025-11-10 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologists', '0005_remove_forms_questions_forms_questions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DueTests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('form_response', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='due_test', to='psychologists.form_response')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='due_tests_patients', to=settings.AUTH_USER_MODEL)),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='due_tests_psychologists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
