# Generated by Django 5.2 on 2025-05-15 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologists', '0005_alter_psychologist_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psychologist',
            name='id',
        ),
        migrations.AlterField(
            model_name='psychologist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='psychologist_profile', related_query_name='psychologist_profiles', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
