# Generated by Django 5.2.7 on 2025-11-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologists', '0006_duetests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duetests',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
