# Generated by Django 5.2.7 on 2025-11-10 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologists', '0007_alter_duetests_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duetests',
            name='form_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='due_test', to='psychologists.form_response'),
        ),
    ]
