# Generated by Django 5.2.7 on 2025-11-12 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologists', '0008_alter_duetests_form_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duetests',
            name='form_response',
        ),
        migrations.AddField(
            model_name='duetests',
            name='access_code',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='duetests',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='due_test', to='psychologists.forms'),
        ),
    ]
