# Generated by Django 5.2.7 on 2025-11-12 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologists', '0009_remove_duetests_form_response_duetests_access_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_response',
            name='due_test',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_response', to='psychologists.duetests'),
        ),
    ]
