# Generated by Django 5.2.7 on 2025-11-12 09:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologists', '0010_form_response_due_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duetests',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
