# Generated by Django 5.2 on 2025-05-07 21:44

import services.modelServices.generate_id
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=services.modelServices.generate_id.generate_id(), editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
