# Generated by Django 5.2.7 on 2025-10-26 00:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='SleepState',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='SleepState',
        ),
    ]
