# Generated by Django 5.2 on 2025-08-17 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_add_owner_to_community'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_at']},
        ),
    ]
