# Generated by Django 5.2.7 on 2025-10-12 20:14

import django.db.models.deletion
import services.modelServices.generate_id
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0004_alter_post_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(default=services.modelServices.generate_id.generate_id(), editable=False, max_length=20, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('new_post', 'Nuevo Post en Comunidad'), ('post_reply', 'Respuesta a tu Post'), ('post_like', 'Like en tu Post'), ('community_join', 'Nuevo Miembro en Comunidad'), ('mention', 'Mención en Post'), ('system', 'Notificación del Sistema')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=500)),
                ('redirect_url', models.CharField(blank=True, max_length=500, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='community.community')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='community.post')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'), models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx')],
            },
        ),
    ]
